### ISSUE TITLE
512/712 disclaimer

### ISSUE THREAD

**Issue by amazaheri** [openaps/docs#11]
Can we add a note that for 512/712 certain commands like Read Settings, BG Targets and certain Read Basal Profile not available, and requires creating a static json for needed info missing to successfully run the loop.

We can either add a sample of jsons as gist or as @bewest suggested add a new command to generate the base files and have the user updating per their pump settings.

**Comment by danamlewis** [comment]
I can add that to the hardware page, unless you think it should go somewhere else? @amazaheri

**Comment by channemann** [comment]
I wouldn't put the details on the hardware page, but perhaps just a note
there that the 512/712 has some limitations and requires additional
considerations, as detailed in [link to a detailed explanation].

On Mon, Sep 21, 2015 at 3:15 PM, Dana Lewis <notifications@github.com>
wrote:

> I can add that to the hardware page, unless you think it should go
> somewhere else? @amazaheri <https://github.com/amazaheri>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openaps/docs/issues/11#issuecomment-142125245>.
>



-- 
Chris Hannemann
chris.hannemann@gmail.com

**Comment by danamlewis** [comment]
Closing per #12 as the fix. Noted @channemann 's input about putting more in another section later to build out further beyond this basic note.
