### ISSUE TITLE
Add instructions on how to "open loop" 

### ISSUE THREAD

**Issue by endafarrell** [openaps/docs#1151]
Given that:

- my CGM is not yet reliable (FreeStyle Libre > Sony SmartWatch3 downgraded to allow NFC > LibreAlarm(+) on an old android phone > xDrip+ (on same phone) > Nightscout) which might work but I don't have a good setup yet, and,
- that I am still learning how to interpret the OpenAPS pill on Nightscout, and,
- that I don't (yet) have Papertrail setup on my rig

it would be good to be able to "open loop" for a while (i'm thinking of a few days, or until I learn howt to interpret the OpenAPS pill). On gitter @danamlewis recommended setting the pump's temp basal setting to % - it seems like this idea warrants a paragraph somewhere in these docs.

**Comment by endafarrell** [comment]
@danamlewis - you can assign this to me, but I would like a recommendation for "where" to add this.

**Comment by danamlewis** [comment]
(Add to the docs here: http://openaps.readthedocs.io/en/latest/docs/Customize-Iterate/usability-considerations.html#how-do-i-open-loop), please open additional doc PRs if you would like to add this info, or a link to it elsewhere.
