### ISSUE TITLE
Interacting with the APS

### ISSUE THREAD

**Issue by GlennCoco** [openaps/docs#1160]
I feel for new people to this experience and too the technology that the instructions may warrant something referencing interaction with the system when in open and closed, ie how to enter data such as carbs, bgl, manual bolus, temp basal etc and on which platform, Xdrip+, NS, pump etc.
As I read somewhere that entering data in one of those systems will not apply it to the algorithm and as such the data will not be collected.
There are references through out the docs for things such as IFTTT which could be hyperlinked within this instruction.
Happy to be involved in the construction of this.

**Comment by increddibelly** [comment]
anyone can edit the pages on github and submit pull requests :)
[the docs](https://guides.github.com/features/mastering-markdown/) show how to make links :)
