### ISSUE TITLE
consider using pip to install

### ISSUE THREAD

**Issue by bewest** [openaps/docs#133]
I think I'm now recommending to use `pip install -U openaps` to install/update openaps.  Fingers crossed, it should pull in everything else appropriately, let me know if any problems.

Tips using pip: the install argument will also take an url to a tarball, or with a little extra keyword, can even take arbitrary urls, here are examples to install dev branches:

* `pip install git+git://github.com/openaps/openaps.git'#dev'`
* `pip install git+git://github.com/bewest/decoding-carelink.git'#dev'``

**Comment by JaysonEwer** [comment]
Hi Ben,

I just tried this on my Edison and got the following messages.  Do I just need to do use sudo?

Thanks,

Jayson

edison@Ewer-Edison-OpenAPS-31:~/openaps$ openaps --version
openaps 0.1.0-dev
edison@Ewer-Edison-OpenAPS-31:~/openaps$

Linux Ewer-Edison-OpenAPS-31 3.10.17-yocto-standard-r2 #7 SMP PREEMPT Thu Feb 26 09:57:06 UTC 2015 i686

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Tue Apr 26 21:34:54 2016 from 192.168.1.8
edison@Ewer-Edison-OpenAPS-31:~$ cd openaps/edison@Ewer-Edison-OpenAPS-31:~/openaps$ pip install -U openaps
Downloading/unpacking openaps from https://pypi.python.org/packages/be/f4/3470311dad060349bf747c537c4fcbf9b03649d3fdb5035956f0d85a89ee/openaps-0.1.0.tar.gz#md5=8be6e9e2bbbbc850d7d43ce82646918a
  Downloading openaps-0.1.0.tar.gz
  Running setup.py (path:/tmp/pip-build-_enrap/openaps/setup.py) egg_info for package openaps
    
Requirement already up-to-date: pyserial in /usr/local/lib/python2.7/dist-packages/pyserial-3.0.1-py2.7.egg (from openaps)
Requirement already up-to-date: python-dateutil in /usr/local/lib/python2.7/dist-packages/python_dateutil-2.5.3-py2.7.egg (from openaps)
Requirement already up-to-date: argcomplete in /usr/local/lib/python2.7/dist-packages/argcomplete-1.1.1-py2.7.egg (from openaps)
Downloading/unpacking gitpython from https://pypi.python.org/packages/03/0c/f341810216c27649e8242e9a4a9041f8484381a5c913b3bf92b93971bea0/GitPython-2.0.1-py2.py3-none-any.whl#md5=fe1a011007d522fb66ea7e90197a73cc (from openaps)
  Downloading GitPython-2.0.1-py2.py3-none-any.whl (425kB): 425kB downloaded
Requirement already up-to-date: mock in /usr/local/lib/python2.7/dist-packages/mock-2.0.0-py2.7.egg (from openaps)
Requirement already up-to-date: nose in /usr/local/lib/python2.7/dist-packages/nose-1.3.7-py2.7.egg (from openaps)
Downloading/unpacking decocare>=0.0.20 from https://pypi.python.org/packages/c1/5d/15f21f2a21963ac45de78809b6f496789366865c383810f5f925f7c06c72/decocare-0.0.23.tar.gz#md5=a95b405572a7bb9fa2fb2b6a7234a368 (from openaps)
  Downloading decocare-0.0.23.tar.gz (78kB): 78kB downloaded
  Running setup.py (path:/tmp/pip-build-_enrap/decocare/setup.py) egg_info for package decocare
    
    warning: no files found matching 'CHANGES.*'
Requirement already up-to-date: dexcom_reader>0.0.5 in /home/edison/src/dexcom_reader (from openaps)
Requirement already up-to-date: six>=1.5 in /usr/local/lib/python2.7/dist-packages/six-1.10.0-py2.7.egg (from python-dateutil->openaps)
Requirement already up-to-date: gitdb>=0.6.4 in /usr/local/lib/python2.7/dist-packages/gitdb-0.6.4-py2.7-linux-i686.egg (from gitpython->openaps)
Downloading/unpacking funcsigs>=1 from https://pypi.python.org/packages/69/cb/f5be453359271714c01b9bd06126eaf2e368f1fddfff30818754b5ac2328/funcsigs-1.0.2-py2.py3-none-any.whl#md5=701d58358171f34b6d1197de2923a35a (from mock->openaps)
  Downloading funcsigs-1.0.2-py2.py3-none-any.whl
Requirement already up-to-date: pbr>=0.11 in /usr/local/lib/python2.7/dist-packages/pbr-1.9.1-py2.7.egg (from mock->openaps)
Requirement already up-to-date: smmap>=0.8.5 in /usr/local/lib/python2.7/dist-packages/smmap-0.9.0-py2.7.egg (from gitdb>=0.6.4->gitpython->openaps)
Installing collected packages: openaps, gitpython, decocare, funcsigs
  Found existing installation: openaps 0.1.0.dev0
    Can't uninstall 'openaps'. No files were found to uninstall.
  Running setup.py install for openaps
    
    changing mode of build/scripts-2.7/openaps from 644 to 755
    changing mode of build/scripts-2.7/openaps-device from 644 to 755
    changing mode of build/scripts-2.7/openaps-use from 644 to 755
    changing mode of build/scripts-2.7/openaps-report from 644 to 755
    changing mode of build/scripts-2.7/openaps-vendor from 644 to 755
    changing mode of build/scripts-2.7/openaps-alias from 644 to 755
    changing mode of build/scripts-2.7/openaps-import from 644 to 755
    error: could not create '/usr/local/lib/python2.7/dist-packages/openaps': Permission denied
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-_enrap/openaps/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-_sFtg6-record/install-record.txt --single-version-externally-managed --compile:
    running install

running build

running build_py

creating build

creating build/lib.linux-i686-2.7

creating build/lib.linux-i686-2.7/tests

copying tests/__init__.py -> build/lib.linux-i686-2.7/tests

creating build/lib.linux-i686-2.7/openaps

copying openaps/builtins.py -> build/lib.linux-i686-2.7/openaps

copying openaps/config.py -> build/lib.linux-i686-2.7/openaps

copying openaps/__init__.py -> build/lib.linux-i686-2.7/openaps

copying openaps/init.py -> build/lib.linux-i686-2.7/openaps

copying openaps/configurable.py -> build/lib.linux-i686-2.7/openaps

creating build/lib.linux-i686-2.7/tests/vendors

copying tests/vendors/test_medtronic.py -> build/lib.linux-i686-2.7/tests/vendors

copying tests/vendors/__init__.py -> build/lib.linux-i686-2.7/tests/vendors

creating build/lib.linux-i686-2.7/tests/glucose

copying tests/glucose/test_display.py -> build/lib.linux-i686-2.7/tests/glucose

copying tests/glucose/test_convert.py -> build/lib.linux-i686-2.7/tests/glucose

copying tests/glucose/__init__.py -> build/lib.linux-i686-2.7/tests/glucose

creating build/lib.linux-i686-2.7/openaps/vendors

copying openaps/vendors/medtronic.py -> build/lib.linux-i686-2.7/openaps/vendors

copying openaps/vendors/process.py -> build/lib.linux-i686-2.7/openaps/vendors
copying openaps/vendors/dexcom.py -> build/lib.linux-i686-2.7/openaps/vendors

copying openaps/vendors/__init__.py -> build/lib.linux-i686-2.7/openaps/vendors

copying openaps/vendors/units.py -> build/lib.linux-i686-2.7/openaps/vendors

creating build/lib.linux-i686-2.7/openaps/devices

copying openaps/devices/add.py -> build/lib.linux-i686-2.7/openaps/devices

copying openaps/devices/show.py -> build/lib.linux-i686-2.7/openaps/devices

copying openaps/devices/remove.py -> build/lib.linux-i686-2.7/openaps/devices

copying openaps/devices/__init__.py -> build/lib.linux-i686-2.7/openaps/devices

copying openaps/devices/device.py -> build/lib.linux-i686-2.7/openaps/devices

creating build/lib.linux-i686-2.7/openaps/monitors

copying openaps/monitors/__init__.py -> build/lib.linux-i686-2.7/openaps/monitors

creating build/lib.linux-i686-2.7/openaps/reports

copying openaps/reports/add.py -> build/lib.linux-i686-2.7/openaps/reports

copying openaps/reports/show.py -> build/lib.linux-i686-2.7/openaps/reports

copying openaps/reports/report.py -> build/lib.linux-i686-2.7/openaps/reports

copying openaps/reports/remove.py -> build/lib.linux-i686-2.7/openaps/reports

copying openaps/reports/invoke.py -> build/lib.linux-i686-2.7/openaps/reports

copying openaps/reports/__init__.py -> build/lib.linux-i686-2.7/openaps/reports

creating build/lib.linux-i686-2.7/openaps/suggesters

copying openaps/suggesters/__init__.py -> build/lib.linux-i686-2.7/openaps/suggesters

creating build/lib.linux-i686-2.7/openaps/controllers

copying openaps/controllers/__init__.py -> build/lib.linux-i686-2.7/openaps/controllers

creating build/lib.linux-i686-2.7/openaps/cli

copying openaps/cli/helpers.py -> build/lib.linux-i686-2.7/openaps/cli

copying openaps/cli/__init__.py -> build/lib.linux-i686-2.7/openaps/cli

copying openaps/cli/commandmapapp.py -> build/lib.linux-i686-2.7/openaps/cli

copying openaps/cli/subcommand.py -> build/lib.linux-i686-2.7/openaps/cli

creating build/lib.linux-i686-2.7/openaps/alias

copying openaps/alias/alias.py -> build/lib.linux-i686-2.7/openaps/alias

copying openaps/alias/add.py -> build/lib.linux-i686-2.7/openaps/alias

copying openaps/alias/show.py -> build/lib.linux-i686-2.7/openaps/alias

copying openaps/alias/remove.py -> build/lib.linux-i686-2.7/openaps/alias

copying openaps/alias/__init__.py -> build/lib.linux-i686-2.7/openaps/alias

creating build/lib.linux-i686-2.7/openaps/glucose

copying openaps/glucose/convert.py -> build/lib.linux-i686-2.7/openaps/glucose
copying openaps/glucose/display.py -> build/lib.linux-i686-2.7/openaps/glucose
copying openaps/glucose/__init__.py -> build/lib.linux-i686-2.7/openaps/glucose

creating build/lib.linux-i686-2.7/openaps/uses

copying openaps/uses/registry.py -> build/lib.linux-i686-2.7/openaps/uses

copying openaps/uses/use.py -> build/lib.linux-i686-2.7/openaps/uses

copying openaps/uses/__init__.py -> build/lib.linux-i686-2.7/openaps/uses

creating build/lib.linux-i686-2.7/openaps/vendors/plugins

copying openaps/vendors/plugins/add.py -> build/lib.linux-i686-2.7/openaps/vendors/plugins

copying openaps/vendors/plugins/show.py -> build/lib.linux-i686-2.7/openaps/vendors/plugins

copying openaps/vendors/plugins/remove.py -> build/lib.linux-i686-2.7/openaps/vendors/plugins

copying openaps/vendors/plugins/__init__.py -> build/lib.linux-i686-2.7/openaps/vendors/plugins

copying openaps/vendors/plugins/vendor.py -> build/lib.linux-i686-2.7/openaps/vendors/plugins

creating build/lib.linux-i686-2.7/openaps/reports/reporters

copying openaps/reports/reporters/stdout.py -> build/lib.linux-i686-2.7/openaps/reports/reporters

copying openaps/reports/reporters/JSON.py -> build/lib.linux-i686-2.7/openaps/reports/reporters

copying openaps/reports/reporters/__init__.py -> build/lib.linux-i686-2.7/openaps/reports/reporters

copying openaps/reports/reporters/text.py -> build/lib.linux-i686-2.7/openaps/reports/reporters

copying openaps/reports/reporters/base.py -> build/lib.linux-i686-2.7/openaps/reports/reporters

running egg_info

writing requirements to openaps.egg-info/requires.txt

writing openaps.egg-info/PKG-INFO

writing top-level names to openaps.egg-info/top_level.txt

writing dependency_links to openaps.egg-info/dependency_links.txt

writing entry points to openaps.egg-info/entry_points.txt

warning: manifest_maker: standard file '-c' not found



reading manifest file 'openaps.egg-info/SOURCES.txt'

reading manifest template 'MANIFEST.in'

writing manifest file 'openaps.egg-info/SOURCES.txt'

running build_scripts

creating build/scripts-2.7

copying and adjusting bin/openaps -> build/scripts-2.7

copying and adjusting bin/openaps-device -> build/scripts-2.7

copying and adjusting bin/openaps-use -> build/scripts-2.7

copying and adjusting bin/openaps-report -> build/scripts-2.7

copying and adjusting bin/openaps-vendor -> build/scripts-2.7

copying and adjusting bin/openaps-alias -> build/scripts-2.7

copying and adjusting bin/openaps-import -> build/scripts-2.7

copying bin/git-openaps-init -> build/scripts-2.7

copying bin/openaps-install-udev-rules -> build/scripts-2.7

changing mode of build/scripts-2.7/openaps from 644 to 755

changing mode of build/scripts-2.7/openaps-device from 644 to 755

changing mode of build/scripts-2.7/openaps-use from 644 to 755

changing mode of build/scripts-2.7/openaps-report from 644 to 755

changing mode of build/scripts-2.7/openaps-vendor from 644 to 755

changing mode of build/scripts-2.7/openaps-alias from 644 to 755

changing mode of build/scripts-2.7/openaps-import from 644 to 755

running install_lib

creating /usr/local/lib/python2.7/dist-packages/openaps

error: could not create '/usr/local/lib/python2.7/dist-packages/openaps': Permission denied

----------------------------------------
  Can't roll back openaps; was not uninstalled
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-_enrap/openaps/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-_sFtg6-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-_enrap/openaps
Storing debug log for failure in /home/edison/.pip/pip.log
edison@Ewer-Edison-OpenAPS-31:~/openaps$

**Comment by JaysonEwer** [comment]
I tried with sudo and got the following output.

I'll try the upgrade to DEV with the following:

pip install git+git://github.com/openaps/openaps.git'#dev'

edison@Ewer-Edison-OpenAPS-31:~/openaps$ openaps --version
openaps 0.1.0-dev
edison@Ewer-Edison-OpenAPS-31:~/openaps$ sudo pip install -U openaps
[sudo] password for edison: 
Downloading/unpacking openaps from https://pypi.python.org/packages/be/f4/3470311dad060349bf747c537c4fcbf9b03649d3fdb5035956f0d85a89ee/openaps-0.1.0.tar.gz#md5=8be6e9e2bbbbc850d7d43ce82646918a
  Downloading openaps-0.1.0.tar.gz
  Running setup.py (path:/tmp/pip-build-hH1fI2/openaps/setup.py) egg_info for package openaps
    
Requirement already up-to-date: pyserial in /usr/local/lib/python2.7/dist-packages/pyserial-3.0.1-py2.7.egg (from openaps)
Requirement already up-to-date: python-dateutil in /usr/local/lib/python2.7/dist-packages/python_dateutil-2.5.3-py2.7.egg (from openaps)
Requirement already up-to-date: argcomplete in /usr/local/lib/python2.7/dist-packages/argcomplete-1.1.1-py2.7.egg (from openaps)
Downloading/unpacking gitpython from https://pypi.python.org/packages/03/0c/f341810216c27649e8242e9a4a9041f8484381a5c913b3bf92b93971bea0/GitPython-2.0.1-py2.py3-none-any.whl#md5=fe1a011007d522fb66ea7e90197a73cc (from openaps)
  Downloading GitPython-2.0.1-py2.py3-none-any.whl (425kB): 425kB downloaded
Requirement already up-to-date: mock in /usr/local/lib/python2.7/dist-packages/mock-2.0.0-py2.7.egg (from openaps)
Requirement already up-to-date: nose in /usr/local/lib/python2.7/dist-packages/nose-1.3.7-py2.7.egg (from openaps)
Downloading/unpacking decocare>=0.0.20 from https://pypi.python.org/packages/c1/5d/15f21f2a21963ac45de78809b6f496789366865c383810f5f925f7c06c72/decocare-0.0.23.tar.gz#md5=a95b405572a7bb9fa2fb2b6a7234a368 (from openaps)
  Downloading decocare-0.0.23.tar.gz (78kB): 78kB downloaded
  Running setup.py (path:/tmp/pip-build-hH1fI2/decocare/setup.py) egg_info for package decocare
    
    warning: no files found matching 'CHANGES.*'
Requirement already up-to-date: dexcom_reader>0.0.5 in /home/edison/src/dexcom_reader (from openaps)
Requirement already up-to-date: six>=1.5 in /usr/local/lib/python2.7/dist-packages/six-1.10.0-py2.7.egg (from python-dateutil->openaps)
Requirement already up-to-date: gitdb>=0.6.4 in /usr/local/lib/python2.7/dist-packages/gitdb-0.6.4-py2.7-linux-i686.egg (from gitpython->openaps)
Downloading/unpacking funcsigs>=1 from https://pypi.python.org/packages/69/cb/f5be453359271714c01b9bd06126eaf2e368f1fddfff30818754b5ac2328/funcsigs-1.0.2-py2.py3-none-any.whl#md5=701d58358171f34b6d1197de2923a35a (from mock->openaps)
  Downloading funcsigs-1.0.2-py2.py3-none-any.whl
Requirement already up-to-date: pbr>=0.11 in /usr/local/lib/python2.7/dist-packages/pbr-1.9.1-py2.7.egg (from mock->openaps)
Requirement already up-to-date: smmap>=0.8.5 in /usr/local/lib/python2.7/dist-packages/smmap-0.9.0-py2.7.egg (from gitdb>=0.6.4->gitpython->openaps)
Installing collected packages: openaps, gitpython, decocare, funcsigs
  Found existing installation: openaps 0.1.0.dev0
    Can't uninstall 'openaps'. No files were found to uninstall.
  Running setup.py install for openaps
    
    changing mode of build/scripts-2.7/openaps from 644 to 755
    changing mode of build/scripts-2.7/openaps-device from 644 to 755
    changing mode of build/scripts-2.7/openaps-use from 644 to 755
    changing mode of build/scripts-2.7/openaps-report from 644 to 755
    changing mode of build/scripts-2.7/openaps-vendor from 644 to 755
    changing mode of build/scripts-2.7/openaps-alias from 644 to 755
    changing mode of build/scripts-2.7/openaps-import from 644 to 755
    changing mode of /usr/local/bin/openaps-install-udev-rules to 755
    changing mode of /usr/local/bin/git-openaps-init to 755
    changing mode of /usr/local/bin/openaps-import to 755
    changing mode of /usr/local/bin/openaps-alias to 755
    changing mode of /usr/local/bin/openaps-vendor to 755
    changing mode of /usr/local/bin/openaps-report to 755
    changing mode of /usr/local/bin/openaps-use to 755
    changing mode of /usr/local/bin/openaps-device to 755
    changing mode of /usr/local/bin/openaps to 755
  Could not find .egg-info directory in install record for openaps from https://pypi.python.org/packages/be/f4/3470311dad060349bf747c537c4fcbf9b03649d3fdb5035956f0d85a89ee/openaps-0.1.0.tar.gz#md5=8be6e9e2bbbbc850d7d43ce82646918a in /home/edison/src/openaps
  Found existing installation: GitPython 2.0.0
    Uninstalling GitPython:
      Successfully uninstalled GitPython
  Found existing installation: decocare 0.0.23.dev0
    Can't uninstall 'decocare'. No files were found to uninstall.
  Running setup.py install for decocare
    
    warning: no files found matching 'CHANGES.*'
    changing mode of build/scripts-2.7/mm-press-key.py from 644 to 755
    changing mode of build/scripts-2.7/mm-send-comm.py from 644 to 755
    changing mode of build/scripts-2.7/mm-set-suspend.py from 644 to 755
    changing mode of build/scripts-2.7/mm-temp-basals.py from 644 to 755
    changing mode of build/scripts-2.7/mm-decode-history-page.py from 644 to 755
    changing mode of build/scripts-2.7/mm-latest.py from 644 to 755
    changing mode of build/scripts-2.7/mm-bolus.py from 644 to 755
    changing mode of build/scripts-2.7/mm-set-rtc.py from 644 to 755
    changing mode of /usr/local/bin/mm-pretty-csv to 755
    changing mode of /usr/local/bin/mm-set-rtc.py to 755
    changing mode of /usr/local/bin/mm-bolus.py to 755
    changing mode of /usr/local/bin/mm-latest.py to 755
    changing mode of /usr/local/bin/mm-decode-history-page.py to 755
    changing mode of /usr/local/bin/mm-temp-basals.py to 755
    changing mode of /usr/local/bin/mm-set-suspend.py to 755
    changing mode of /usr/local/bin/mm-send-comm.py to 755
    changing mode of /usr/local/bin/mm-press-key.py to 755
  Could not find .egg-info directory in install record for decocare>=0.0.20 from https://pypi.python.org/packages/c1/5d/15f21f2a21963ac45de78809b6f496789366865c383810f5f925f7c06c72/decocare-0.0.23.tar.gz#md5=a95b405572a7bb9fa2fb2b6a7234a368 in /home/edison/src/decoding-carelink (from openaps)
  Found existing installation: funcsigs 1.0.0
    Uninstalling funcsigs:
      Successfully uninstalled funcsigs
Successfully installed openaps gitpython decocare funcsigs
Cleaning up...
edison@Ewer-Edison-OpenAPS-31:~/openaps$

**Comment by JaysonEwer** [comment]
Does this look good to you?

Thanks,

Jayson

edison@Ewer-Edison-OpenAPS-31:~/openaps$ sudo pip install git+git://github.com/openaps/openaps.git'#dev' --upgrade
Downloading/unpacking git+git://github.com/openaps/openaps.git
  Cloning git://github.com/openaps/openaps.git to /tmp/pip-ZMAMcK-build
  Running setup.py (path:/tmp/pip-ZMAMcK-build/setup.py) egg_info for package from git+git://github.com/openaps/openaps.git
    
Requirement already up-to-date: pyserial in /usr/local/lib/python2.7/dist-packages/pyserial-3.0.1-py2.7.egg (from openaps==0.1.0)
Requirement already up-to-date: python-dateutil in /usr/local/lib/python2.7/dist-packages/python_dateutil-2.5.3-py2.7.egg (from openaps==0.1.0)
Requirement already up-to-date: argcomplete in /usr/local/lib/python2.7/dist-packages/argcomplete-1.1.1-py2.7.egg (from openaps==0.1.0)
Requirement already up-to-date: gitpython in /usr/local/lib/python2.7/dist-packages (from openaps==0.1.0)
Requirement already up-to-date: mock in /usr/local/lib/python2.7/dist-packages/mock-2.0.0-py2.7.egg (from openaps==0.1.0)
Requirement already up-to-date: nose in /usr/local/lib/python2.7/dist-packages/nose-1.3.7-py2.7.egg (from openaps==0.1.0)
Downloading/unpacking decocare>=0.0.20 from https://pypi.python.org/packages/c1/5d/15f21f2a21963ac45de78809b6f496789366865c383810f5f925f7c06c72/decocare-0.0.23.tar.gz#md5=a95b405572a7bb9fa2fb2b6a7234a368 (from openaps==0.1.0)
  Downloading decocare-0.0.23.tar.gz (78kB): 78kB downloaded
  Running setup.py (path:/tmp/pip-build-fiEuLA/decocare/setup.py) egg_info for package decocare
    
    warning: no files found matching 'CHANGES.*'
Requirement already up-to-date: dexcom_reader>0.0.5 in /home/edison/src/dexcom_reader (from openaps==0.1.0)
Requirement already up-to-date: six>=1.5 in /usr/local/lib/python2.7/dist-packages/six-1.10.0-py2.7.egg (from python-dateutil->openaps==0.1.0)
Requirement already up-to-date: funcsigs>=1 in /usr/local/lib/python2.7/dist-packages (from mock->openaps==0.1.0)
Requirement already up-to-date: pbr>=0.11 in /usr/local/lib/python2.7/dist-packages/pbr-1.9.1-py2.7.egg (from mock->openaps==0.1.0)
Installing collected packages: decocare, openaps
  Found existing installation: decocare 0.0.23.dev0
    Can't uninstall 'decocare'. No files were found to uninstall.
  Running setup.py install for decocare
    
    warning: no files found matching 'CHANGES.*'
    changing mode of build/scripts-2.7/mm-press-key.py from 644 to 755
    changing mode of build/scripts-2.7/mm-send-comm.py from 644 to 755
    changing mode of build/scripts-2.7/mm-set-suspend.py from 644 to 755
    changing mode of build/scripts-2.7/mm-temp-basals.py from 644 to 755
    changing mode of build/scripts-2.7/mm-decode-history-page.py from 644 to 755
    changing mode of build/scripts-2.7/mm-latest.py from 644 to 755
    changing mode of build/scripts-2.7/mm-bolus.py from 644 to 755
    changing mode of build/scripts-2.7/mm-set-rtc.py from 644 to 755
    changing mode of /usr/local/bin/mm-pretty-csv to 755
    changing mode of /usr/local/bin/mm-set-rtc.py to 755
    changing mode of /usr/local/bin/mm-bolus.py to 755
    changing mode of /usr/local/bin/mm-latest.py to 755
    changing mode of /usr/local/bin/mm-decode-history-page.py to 755
    changing mode of /usr/local/bin/mm-temp-basals.py to 755
    changing mode of /usr/local/bin/mm-set-suspend.py to 755
    changing mode of /usr/local/bin/mm-send-comm.py to 755
    changing mode of /usr/local/bin/mm-press-key.py to 755
  Could not find .egg-info directory in install record for decocare>=0.0.20 from https://pypi.python.org/packages/c1/5d/15f21f2a21963ac45de78809b6f496789366865c383810f5f925f7c06c72/decocare-0.0.23.tar.gz#md5=a95b405572a7bb9fa2fb2b6a7234a368 in /home/edison/src/decoding-carelink (from openaps==0.1.0)
  Found existing installation: openaps 0.1.0.dev0
    Can't uninstall 'openaps'. No files were found to uninstall.
  Running setup.py install for openaps
    
    changing mode of build/scripts-2.7/openaps from 644 to 755
    changing mode of build/scripts-2.7/openaps-device from 644 to 755
    changing mode of build/scripts-2.7/openaps-use from 644 to 755
    changing mode of build/scripts-2.7/openaps-report from 644 to 755
    changing mode of build/scripts-2.7/openaps-vendor from 644 to 755
    changing mode of build/scripts-2.7/openaps-alias from 644 to 755
    changing mode of build/scripts-2.7/openaps-import from 644 to 755
    changing mode of /usr/local/bin/openaps-install-udev-rules to 755
    changing mode of /usr/local/bin/git-openaps-init to 755
    changing mode of /usr/local/bin/openaps-import to 755
    changing mode of /usr/local/bin/openaps-alias to 755
    changing mode of /usr/local/bin/openaps-vendor to 755
    changing mode of /usr/local/bin/openaps-report to 755
    changing mode of /usr/local/bin/openaps-use to 755
    changing mode of /usr/local/bin/openaps-device to 755
    changing mode of /usr/local/bin/openaps to 755
  Could not find .egg-info directory in install record for openaps==0.1.0 from git+git://github.com/openaps/openaps.git
Successfully installed decocare openaps
Cleaning up...
edison@Ewer-Edison-OpenAPS-31:~/openaps$

**Comment by bewest** [comment]
Looks like maybe the github email interface is broken somehow?  That's embarrassing, but somehow I saw your traces come through email, but they don't appear at all on the web interface.  Maybe the `sudo` version worked?  I'm sorry the Github email interface appears to be broken, especially, it does not handle attachments at all :-(.

**Comment by bewest** [comment]
Somehow, some of the comments came through email.  It more or less looks ok.
Curious what `openaps --version` says.

**Comment by scottleibrand** [comment]
So where are we with this?  Is it working well?  Should we update docs to reference this instead of quick-packages / quick-src?  Or should we update those to do this?

**Comment by bewest** [comment]
It seems to be working well, and will simplify needing to update setuptools.  I did have an issue with installing udev rules.  In any case, I look forward to getting feedback on using `pip` so that if anything is wrong I can fix it.

**Comment by bewest** [comment]
I've been using it over last month or so and been recommending it as well.  One of the benefits is that `pip` will accept a simple git url pointing at a branch, which should eliminate the need to maintain git clones.

**Comment by bewest** [comment]
Bump...

**Comment by Spazholio** [comment]
So far, I haven't had any issues that I can recall with using `pip`.  I'm in favor of advocating it over maintaining `src` dirs.

**Comment by scottleibrand** [comment]
Agreed. Just need someone to update all the docs.

**Comment by scottleibrand** [comment]
Updated https://github.com/openaps/docs/blob/master/scripts/quick-packages.sh - closing.
