### ISSUE TITLE
suggestion making requirements for rig more clear (especially explorer HAT)

### ISSUE THREAD

**Issue by littlepingwing** [openaps/docs#1420]
Hello dear makers,

as most people posting here, I've started building my own rig. However, I ran into a few problems. Most of them where my fault of course, but I'd like to prevent other people from making the same mistakes.

The mistake: ordering an "explorer HAT".
why: because it's called an explorer hat on the openaps.org site.
what to do: make it more clear, avoid calling it a thing that actually exists (and people might order).
how: replacing "explorer HAT" with "Pi radio 868MHz/915MHz HAT" or something alike.

thank you for your time,
I hope after this mistake I will be able to finish making the rig 👍 ,
Anja

**Comment by scottleibrand** [comment]
It looks like “900MHz explorer hat” is probably the phrase we should use to make sure people find the right one, along with links of course. Would you like to suggest edits to the pages where it would have been most helpful to have the additional context?

**Comment by littlepingwing** [comment]
there are a few places where it would be nice to be changed, I would've done it myself if I could edit it but I can't. I'd change it at least on the following pages:
Hardware overview,
get your rig hardware, also change the title here.

**Comment by danamlewis** [comment]
@littlepingwing, the docs are open source so you can edit yourself & suggest those changes! Here's a guide of how to make edits, if you haven't done it before: https://openaps.readthedocs.io/en/latest/docs/Resources/my-first-pr.html

(So for example, look for the edit button on the top right of the page where you think changes should be made)

<img width="774" alt="screen shot 2019-02-17 at 1 38 03 pm" src="https://user-images.githubusercontent.com/7468165/52919652-69fc6d00-32b9-11e9-84e1-b3a1d4885e1d.png">

**Comment by littlepingwing** [comment]
thank you, 
I tried editing through the menu on the bottom left - this doesn't work. The button on the top right does!

**Comment by danamlewis** [comment]
@littlepingwing great! I haven't seen a PR come in - I'm guessing you may have saved the changes to your branch, but still need to open the PR back to OpenAPS's branch so we can review those changes.

**Comment by mrengy** [comment]
@littlepingwing [This guide on submitting a pull request (PR)](https://help.github.com/en/articles/creating-a-pull-request) might be helpful
