### ISSUE TITLE
Debian Jessie has lost upstream support

### ISSUE THREAD

**Issue by cluckj** [openaps/docs#1447]
The package mirrors and apt repositories for debian jessie have been deprecated: https://lists.debian.org/debian-devel-announce/2019/03/msg00006.html

We should probably change the docs to recommend jubilinux 0.3 (stretch), and recommend reflashing for folks who are using jubilinux 0.2 (jessie).

(I'm creating for discussion of the issue, and to track all the changes we need to make to the docs)

Related: https://github.com/openaps/oref0/issues/1236

**Comment by danamlewis** [comment]
@cluckj
