### ISSUE TITLE
"Get your rig parts" page puts casing info for Edison boards inside "Pi-based setups with rewired TI-stick" section

### ISSUE THREAD

**Issue by Dune-jr** [openaps/docs#1509]
I had some trouble to find info for Cases for Edison plus battery. They are there:  
https://openaps.readthedocs.io/en/latest/docs/Gear%20Up/edison.html?highlight=casing#soft-cases

It seems the sections got messed up by a new update

**Comment by danamlewis** [comment]
Resolved via https://github.com/openaps/docs/commit/69bd475de4480517570abd5c49e8b31d24f5641b to cut down on confusion
