### ISSUE TITLE
Information about Li-Po battery lifetime

### ISSUE THREAD

**Issue by Dune-jr** [openaps/docs#1510]
https://openaps.readthedocs.io/en/latest/docs/Customize-Iterate/usability-considerations.html#improving-the-battery-life-of-your-raspberry-pi claims 

> Version - CPU Clock - Battery Life @ 2500mAh (Li-Po)
0.6.2 - 1000 MHz - 8 hours
0.7.0-dev - 1000 MHz - 9 hours
0.7.0-dev - 500 MHz - 14.5 hours

However, this https://openaps.readthedocs.io/en/latest/docs/Gear%20Up/edison.html#battery says

> A 2000 mah battery is roughly the size of the Raspberry Pi0, and can last around 4 hours.

One of the two should be obsolete, right?

**Comment by danamlewis** [comment]
Different - one is referring to use with Raspberry Pi; the other is referring to Edison battery life use.
