### ISSUE TITLE
Autobuild Documentation for Pull Requests

### ISSUE THREAD

**Issue by StephenBrown2** [openaps/docs#1533]
For the current PRs, it would be great to have the docs built on RTD as they would be when deployed, for easy review and checking that things work the same as they do locally.

RTD has implemented the feature and talks about it here: https://blog.readthedocs.com/building-docs-for-pull-requests/

Since it's currently (as of Oct 2019) in beta, it requires emailing them to set it up:
> Building documentation for pull requests is currently in Beta testing and only supports Github repositories. If you want to dive in and enable this feature for your project you can [email us](mailto:support%40readthedocs.org) with the URL of your ReadtheDocs project.

but I think it would be a valuable thing to have to prevent confusion with PRs such as #1514

**Comment by danamlewis** [comment]
This is now included by default in PRs. Thanks!
