### ISSUE TITLE
MongoDB cluster setup instructions missing from Nightscout install page

### ISSUE THREAD

**Issue by zspitz** [openaps/docs#1557]
While following the instructions on the [OpenAPS Nightscout setup page](https://github.com/openaps/docs/blob/master/docs/docs/While%20You%20Wait%20For%20Gear/nightscout-setup.md), I can't deploy because I am missing the `MONGODB_URI` required field. There's no mention of this field, or what value should be in it.

The [Nightscout documentation](https://nightscout.github.io/nightscout/new_user/) describes creating an Atlas account and a MongoDB cluster, and the value used for `MONGODB_URI`.

**Comment by scottleibrand** [comment]
If you don't need to transition existing data from Azure to Heroku, I don't know that it's necessary to follow the "Switching from Azure to Heroku" instructions. Are you trying to set up a new instance, or do you already have one you're trying to migrate, or something else?

**Comment by zspitz** [comment]
To  my knowledge, I didn't previously have any data in Azure, but I was still prompted for a `MONGODB_URI` value.

**Comment by scottleibrand** [comment]
If the OpenAPS docs' instructions for setting up Nightscout (which isn't really part of OpenAPS) are out of date, you should use the Nightscout instructions instead, and let us know (preferably via a PR) which part of the OpenAPS docs are incorrect and need to be removed and replaced with a reference to the Nightscout docs.

**Comment by danamlewis** [comment]
NS page within OpenAPS is updated with a link and encouragement to follow the latest NS setup instructions before updating with the OpenAPS-related config variables.
