### ISSUE TITLE
Add Flashing Troubleshooting to the Main Nav

### ISSUE THREAD

**Issue by old-square-eyes** [openaps/docs#1559]
My PR was accepted...

https://openaps.readthedocs.io/en/latest/docs/Troubleshooting/Flashing-and-updating-Jubilinux.html

Can I please have it added to the main Nav, under troubleshooting?

FYI @danamlewis

**Comment by scottleibrand** [comment]
That just requires a PR to https://github.com/openaps/docs/blob/master/docs/docs/Troubleshooting/index.rst

**Comment by old-square-eyes** [comment]
Cool: https://github.com/openaps/docs/pull/1560

**Comment by danamlewis** [comment]
https://github.com/openaps/docs/pull/1560#issuecomment-727024644
