### ISSUE TITLE
Does this still work after mLab MongoDB add-on removed from Heroku?

### ISSUE THREAD

**Issue by fbeels** [openaps/docs#1566]
Sorry if this is the wrong place to ask (I didn't see any forums to ask this) and sorry if this a newb question answered somewhere else.

I started building my rig a year ago and well covid happened and I shelved the project. I'm now looking to get back into it, and buried in my spam folder was a notification from Heroku saying "mLab MongoDB add-on will be removed from all Heroku apps on November 10, 2020"

I followed the instructions word for word last year and I thought adding MongoDB was a required step,  is everything broken now? I can't tell if the instructions were updated since MongoDB has been deleted.

**Comment by rland93** [comment]
I just went through this (similar situation as yourself).

You can set up Nightscout with a free mongodb instance on MongoDB Atlas. It's described here: https://nightscout.github.io/nightscout/new_user/. There is another open issue about the lack of documentation here: https://github.com/openaps/docs/issues/1557 

I'm not sure how you would migrate an existing nightscout instance -- I just opted to reinstall. Hope this helps!

**Comment by danamlewis** [comment]
NS page within OpenAPS is updated with a link and encouragement to follow the latest NS setup instructions before updating with the OpenAPS-related config variables.
