### ISSUE TITLE
nodejs-legacy broken -- breaks npm

### ISSUE THREAD

**Issue by ehwest** [openaps/docs#201]
there is this line in the instructions script.

sudo apt-get install -y git python python-dev python-software-properties python-numpy python-pip nodejs-legacy npm watchdog

This script breaks when trying to install nodejs-legacy.
In additon, that break, causes the rest of the line, including installation of npm and watchdog to fail.
This causes openaps installation to fail.

**Comment by scottleibrand** [comment]
What OS and distribution is this failing on?

**Comment by scottleibrand** [comment]
Are you still seeing this?  Any more info you can provide?

**Comment by scottleibrand** [comment]
Please reopen if you can provide more details or see this again.

**Comment by formlinksystemslimited** [comment]
This is still broken - running curl -s https://raw.githubusercontent.com/openaps/docs/master/scripts/quick-packages.sh | bash -
from https://openaps.readthedocs.io/en/stable/docs/walkthrough/phase-0/openaps.html

initially results in:
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?

then the script outputs:
Package nodejs-legacy is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  nodejs libnode64

E: Package 'nodejs-legacy' has no installation candidate
pi@raspberrypi:~ $_

when processing the line: _sudo apt-get -o Acquire::ForceIPv4=true install -y git python python-dev software-properties-common python-numpy python-pip nodejs-legacy npm watchdog strace tcpdump screen acpid vim locate jq lm-sensors bc && \_ 
in the script being executed.

this was on a brand new setup today - with the following OS details:
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

Running on a Raspberry PI Zero WH


nodejs-legacy is nolonger available,
according to https://nodejs.org/en/download/ jodejs is no longer supported on ARMv6 (Pi Zero)
