### ISSUE TITLE
broken TOC

### ISSUE THREAD

**Issue by tghoward** [openaps/docs#25]
hmmm, the table of contents is broken online.  Will try to sleuth it out but may not be able to.

**Comment by tghoward** [comment]
crud. Building locally from a fresh copy of master does not reproduce the problem.

**Comment by scottleibrand** [comment]
I think gitbooks might be "stuck": I don't think updates are showing
either.  If anyone has any ideas for unsticking it...

**Comment by channemann** [comment]
Just contact them; they're very responsive.

On Thu, Nov 5, 2015 at 2:56 PM, Scott Leibrand <notifications@github.com>
wrote:

> I think gitbooks might be "stuck": I don't think updates are showing
> either. If anyone has any ideas for unsticking it...
>
> On Thu, Nov 5, 2015 at 3:38 PM, Tim Howard <notifications@github.com>
> wrote:
>
> > crud. Building locally from a fresh copy of master does not reproduce the
> > problem.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/openaps/docs/issues/25#issuecomment-154218075>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openaps/docs/issues/25#issuecomment-154222159>.
>



-- 
Chris Hannemann
chris.hannemann@gmail.com

**Comment by scottleibrand** [comment]
This was fixed at D-data when I added TOC to each main page.
