### ISSUE TITLE
structure of outline overall

### ISSUE THREAD

**Issue by julieraines** [openaps/docs#302]
I.  Introduction (with BIG PICTURE which I will start a PR on)

II.  General Setup 
          Consider eliminating the concept of "Walkthrough" which discourages people from reading the intro and skipping to the "Walkthrough", it also suggests that these instructions are complete and perfect which discourages people submitting PRs (it must be something I'm doing wrong, not the instructions)
          Phases are nice to show progression however this requires a lot outside of the phases and if PRs are integral to this process, they should be a part of the process rather than "outside" the phases

III.  Nightscout part 1 here
          Since folks who come here are mainly familiar with this, it's a nice way to ease into it

IV.  OpenAPS 
          What is OpenAPS first before how to set it up

V.  Creating an open loop

VI.  Closing the loop 
          NS part 2 somewhere between the last part and this one

VII.  Turning the closed loop

VIII.  Iterate and improve

IX.  Resources

X.  References

**Comment by sarahspins** [comment]
I feel like some of the NS stuff was already broken up appropriately, like when it was first introduced if you wanted to pull BG data from NS (I actually had zero issues doing that before I figured out how to successfully pull data from my G5).  The problem does come later when the bulk of it is introduced, and the way it is introduced with the templates - there is some stuff missing and definitely some things out of order and/or not explained well at all.  Maybe some of that is intentional, but for someone trying to figure it all out for the first time, it is problematic, and very difficult to see "am I just not getting it" or "is something actually not working".

I think the biggest help would actually be to add little "if that didn't work, this might be why" suggestions throughout the docs.

**Comment by scottleibrand** [comment]
:+1:

If y'all want, you can probably start PR'ing a lot of these suggested changes in right now. For some of the reorganization stuff that might require a few revisions, you're also welcome to PR that to dev first.

**Comment by julieraines** [comment]
ok - I hesitated to PR structural changes because I'm wrapping my brain around how-to but I imagine it's a copy/paste/rename thing so doing this to dev makes total sense.  the dividing up NS was someone else's idea (Dragan) and he's going to work on that so I'll let that sleepin' dawg lie (LOL)

**Comment by scottleibrand** [comment]
Yeah, if you're not just moving/renaming files but actually moving content between files, copy-paste is easiest.

**Comment by julieraines** [comment]
Yes - moving/renaming without migrating content would be VERY bad

**Comment by julieraines** [comment]
How is the order of files determined?  So that I can just PR a move?  Some content needs to be moved, too, but the files themselves should be flipped in some instances.

**Comment by dm61** [comment]
What do you think about [this diagram](https://docs.google.com/presentation/d/1QuhJqb0fNlfmTuTYZS2t2QtPaiosA2k1uo7DZFQxtUY/edit?usp=sharing)?

**Comment by scottleibrand** [comment]
@julieraines can you clarify? Not sure I understand the question.

**Comment by julieraines** [comment]
You mean you can't read my mind?!?  ha ha  OK - so if within OPENAPS GUIDE I want to do a PR to move OVERVIEW so that it comes before INSTALLING instead of the other way around (which is how it is now), then how do I do that?  I think that part of OVERVIEW will also get copied into INSTALLING (MY FIRST WORKSPACE) but usually an overview of something comes before you actually start working in it.  Does this make sense?

**Comment by scottleibrand** [comment]
Good question: I had to do some digging to figure it out.

Looks like you want to edit https://raw.githubusercontent.com/openaps/docs/master/docs/docs/openaps-guide/index.rst

To get there I went to https://github.com/openaps/docs/tree/master/docs/docs/openaps-guide, clicked index.rst, and then clicked Raw.  Clicking the Edit pencil button also works, but unfortunately when Github renders it as markdown, it hides all the important details like the list of pages and what order they go in.  :-)

**Comment by julieraines** [comment]
OK - so I asked something that wasn't overtly obvious?!?  very cool.  I will try it  . . . SO excited.

**Comment by danamlewis** [comment]
@julieraines - closing this issue, but re-open after you look at the new flow (http://openaps.readthedocs.org/en/dev/) if you still want to discuss structural organization changes, we've made many changes to the docs since this discussion.
