### ISSUE TITLE
Phase 2 naming conflicts

### ISSUE THREAD

**Issue by dakago** [openaps/docs#318]
There are currently a number of differences between the names used in the newer oref0 templates and the current walkthrough which I believe has caused some confusion.  For example: bg_targets_raw.json in the docs is bg-targets-raw.json in the templates as well as things like settings/insulin_sensitivities_raw.json in the docs is raw-pump/insulin-sensitivities-raw.json in the templates. I was thinking about doing a PR to try to straighten things out a bit but will it even be necessary with the new style walkthrough that uses templates? Is this section going to be reduced to templates or still have explanations on how everything works and how to create it?  Seems like it is kind of important for the DIY part of it but the templates are nice!  At the very least maybe just adding a warning that the names don't match and will have to be altered?

**Comment by scottleibrand** [comment]
I would start cleaning things up and submitting PRs. If you can / want to simplify things further with more template use as well, that is also great. I don't think anyone has a master plan for that, so incremental improvements are the way to go. Thanks!

**Comment by danamlewis** [comment]
Closing since resolved with the new setup script workflow outlined in docs.
