### ISSUE TITLE
Walkthrough invokes oref0 tools too early (before explained or mentioned) 

### ISSUE THREAD

**Issue by elnjensen** [openaps/docs#335]
In Phase 1 of the walkthrough, in file `using-openaps-tools.md`, there is a line that says:

Create bunch of reports:
`oref0 template mint reports medtronic-pump | openaps import`

If the user runs that command (which it seems like he/she is supposed to), this adds about 25 reports to the user's openaps.ini, including with subdirectories that aren't created yet, devices (units) that don't exist yet, etc.  

So then it's confusing later in that file when the walkthrough implies that openaps.ini should be relatively empty, that you should know what each report does when you add it, and so on.  Should this command just be cut?  oref0 hasn't even been mentioned previously at this point, I don't think. 

This same command (along with a few other oref0 invocations) occurs in a pretty confusing section at the beginning of `phase-2/Using-oref0-tools.md`.  There at least there is a note that says that this part of the docs is out of date and that the usage in different parts of the file doesn't match.  But as a new user going through it I had little idea what to do or not to do at this point.  It seems like skipping those oref0 invocations at the top makes the most sense, in the context of the walkthrough as it stands, but having the user have to guess which commands to skip isn't ideal.

**Comment by danamlewis** [comment]
Closing since resolved with the new setup scripts flow.
