### ISSUE TITLE
Additonal supported HW

### ISSUE THREAD

**Issue by beached** [openaps/docs#340]
Should be able to add the Veo 754CML with FW 2.7A to the list of devices with MySentry support at https://github.com/openaps/docs/blob/master/docs/docs/walkthrough/phase-0/hardware.md

Been using it with Loop for several days now and prior RileyLink iOS.  This is the Canadian Veo 754 with the same frequencies as the US but mmol/L

**Comment by danamlewis** [comment]
Great - added: https://github.com/openaps/docs/commit/e63ec79f10e8af69629574998b46b74881755a5b
