### ISSUE TITLE
Broken link to wifi troubleshooting

### ISSUE THREAD

**Issue by bfaloona** [openaps/docs#361]
The 'wifi troubleshooting page' link on this page is broken:
http://openaps.readthedocs.io/en/latest/docs/Resources/troubleshooting.html
The link is: https://openaps.readthedocs.io/en/latest/docs/Resources/wifi.md.html
It should be: http://openaps.readthedocs.io/en/latest/Resources/wifi.html

Notes:
* Should the file in question be moved to the other Resources folder at /en/latest/docs/Resources/wifi instead of the current location at /en/latest/Resources/wifi ?
* I often get 'This page does not exist yet' when browsing the docs, so I think there may be a few of these link issues.

**Comment by scottleibrand** [comment]
If you want to take a stab at fixing them, you can PR your changes to the dev branch instead of master to see if they get fixed properly without any side effects before PR'ing to master.

**Comment by danamlewis** [comment]
Looks resolved to me, closing.
