### ISSUE TITLE
Local markdown links break on readthedocs.io

### ISSUE THREAD

**Issue by bfaloona** [openaps/docs#371]
Local links in markdown files are broken. For example:

source: https://github.com/openaps/docs/blob/master/docs/reference/openaps/openaps-report-settings-auto-sens.md

redered by sphinx/readthedocs: http://openaps.readthedocs.io/en/latest/reference/openaps/openaps-report-settings-auto-sens.html 

The link target for 'monitor/glucose.json' is `openaps-report-monitor-glucose.md` in markdown, which fails to link properly to:
http://openaps.readthedocs.io/en/latest/reference/openaps/openaps-report-monitor-glucose.html

Even preceeding the target with dot slash ( `./openaps-report-monitor-glucose.md` ) does not work.

It is unclear to me which sphinx extensions are in use. See: https://github.com/openaps/docs/blob/master/docs/conf.py

**Comment by danamlewis** [comment]
@bfaloona - are we still broken? (Check out my latest PR trying to merge dev to master, so use dev RTD to confirm since that's the latest). Let me know if we are, otherwise let's close this issue.

**Comment by danamlewis** [comment]
Closing, please re-open if this is still happening with the new docs. @bfaloona

**Comment by sjezewski** [comment]
Hi there!

I'm seeing this issue.

An example page is [here](http://docs.pachyderm.io/en/latest/pachctl/pachctl.html) which includes a [broken link](http://docs.pachyderm.io/en/latest/pachctl/pachctl_archive-all.md) that should point [to here](http://docs.pachyderm.io/en/latest/pachctl/pachctl_archive-all.html)

I'm happy to try the latest version, but not quite sure how to do that.

**Comment by sjezewski** [comment]
Oops, my mistake. I was bug hunting and thought I was on the RTD repo
