### ISSUE TITLE
I want Help. Try Installing OpenAps - Problems.

### ISSUE THREAD

**Issue by aflizarraga** [openaps/docs#400]
login as: pi
pi@192.168.1.2's password:

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Sun Oct  2 19:17:21 2016
pi@raspberrypi:~ $ sudo easy_install -Z openaps
Processing openaps
Writing /home/pi/openaps/setup.cfg
Running setup.py -q bdist_egg --dist-dir /home/pi/openaps/egg-dist-tmp-z6tJYA
openaps 0.1.6-dev is already the active version in easy-install.pth
Installing openaps-use script to /usr/local/bin
Installing openaps-install-udev-rules script to /usr/local/bin
Installing openaps script to /usr/local/bin
Installing git-openaps-init script to /usr/local/bin
Installing openaps-import script to /usr/local/bin
Installing openaps-alias script to /usr/local/bin
Installing openaps-report script to /usr/local/bin
Installing openaps-vendor script to /usr/local/bin
Installing openaps-device script to /usr/local/bin

Installed /usr/local/lib/python2.7/dist-packages/openaps-0.1.6_dev-py2.7.egg
Processing dependencies for openaps==0.1.6-dev
Searching for mock
Reading https://pypi.python.org/simple/mock/
Best match: mock 2.0.0
Downloading https://pypi.python.org/packages/0c/53/014354fc93c591ccc4abff12c473ad565a2eb24dcd82490fae33dbf2539f/mock-2.0.0.tar.gz#md5=0febfafd14330c9dcaa40de2d82d40ad
Processing mock-2.0.0.tar.gz
Writing /tmp/easy_install-SpnVfK/mock-2.0.0/setup.cfg
Running mock-2.0.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-SpnVfK/mock-2.0.0/egg-dist-tmp-cIKocf
Searching for setuptools>=17.1
Reading https://pypi.python.org/simple/setuptools/
Best match: setuptools 28.2.0
Downloading https://pypi.python.org/packages/fa/dd/e310aaaf1702516e12451d2d5eb78175587edc7fbeb1afd58263171e9384/setuptools-28.2.0.tar.gz#md5=b2031092dcf317cdd140c6c200957c26
Processing setuptools-28.2.0.tar.gz
Writing /tmp/easy_install-SpnVfK/mock-2.0.0/temp/easy_install-Wo461v/setuptools-28.2.0/setup.cfg
Running setuptools-28.2.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-SpnVfK/mock-2.0.0/temp/easy_install-Wo461v/setuptools-28.2.0/egg-dist-tmp-EeX7MB
warning: no files found matching '*' under directory 'setuptools/_vendor'

Installed /tmp/easy_install-SpnVfK/mock-2.0.0/setuptools-28.2.0-py2.7.egg
Searching for pbr>=1.3
Reading https://pypi.python.org/simple/pbr/
Best match: pbr 1.10.0
Downloading https://pypi.python.org/packages/c3/2c/63275fab26a0fd8cadafca71a3623e4d0f0ee8ed7124a5bb128853d178a7/pbr-1.10.0.tar.gz#md5=8e4968c587268f030e38329feb9c8f17
Processing pbr-1.10.0.tar.gz
Writing /tmp/easy_install-SpnVfK/mock-2.0.0/temp/easy_install-XaD6bx/pbr-1.10.0/setup.cfg
Running pbr-1.10.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-SpnVfK/mock-2.0.0/temp/easy_install-XaD6bx/pbr-1.10.0/egg-dist-tmp-DNprPt

Installed /tmp/easy_install-SpnVfK/mock-2.0.0/pbr-1.10.0-py2.7.egg
Marker evaluation failed, see the following error.  For more information see: http://docs.openstack.org/developer/pbr/compatibility.html#evaluate-marker
ERROR:root:Error parsing
Traceback (most recent call last):
  File "/tmp/easy_install-SpnVfK/mock-2.0.0/pbr-1.10.0-py2.7.egg/pbr/core.py", line 111, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "/tmp/easy_install-SpnVfK/mock-2.0.0/pbr-1.10.0-py2.7.egg/pbr/util.py", line 248, in cfg_to_args
    kwargs = setup_cfg_to_setup_kwargs(config, script_args)
  File "/tmp/easy_install-SpnVfK/mock-2.0.0/pbr-1.10.0-py2.7.egg/pbr/util.py", line 431, in setup_cfg_to_setup_kwargs
    if pkg_resources.evaluate_marker('(%s)' % env_marker):
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1306, in evaluate_marker
    return cls.interpret(parser.expr(text).totuple(1)[1])
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1341, in interpret
    return op(nodelist)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1254, in atom
    return cls.interpret(nodelist[2])
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1341, in interpret
    return op(nodelist)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1275, in comparison
    raise SyntaxError(msg)
SyntaxError: '<' operator not allowed in environment markers
error: Setup script exited with error in setup command: Error parsing /tmp/easy_install-SpnVfK/mock-2.0.0/setup.cfg: SyntaxError: '<' operator not allowed in environment markers
pi@raspberrypi:~ $

**Comment by scottleibrand** [comment]
The easy_install command is now deprecated. Where in the docs did you still see that recommended?

http://openaps.readthedocs.io/en/dev/docs/walkthrough/phase-0/openaps.html is the recommended way to install openaps now.

**Comment by aflizarraga** [comment]
El Domingo, 2 de octubre, 2016 20:28:45, Scott Leibrand <notifications@github.com> escribió:
 

 The easy_install command is now deprecated. Where in the docs did you still see that recommended?http://openaps.readthedocs.io/en/dev/docs/walkthrough/phase-0/openaps.html is the recommended way to install openaps now. —
