### ISSUE TITLE
setting up openaps.. stuck trying to upload data to Nightscout

### ISSUE THREAD

**Issue by betluis** [openaps/docs#404]
hello...

After two months of finding the right used pump, getting my daughter to change from injections tu pump, get the CGM sensor, etc... finally I am trying to make progress with the actual implementation of the openaps system. 

I am stuck right now in the process to update data to Nightscout, could somebody please help me?

below
 is the reponse when I do "openaps do-everything"

thsnk a lot for any help!
Luis

-----
pi@raspberrypi:~/my_openaps $ openaps do-everything
PREFLIGHT
PREFLIGHT OK
usage: openaps-report invoke [-h]
                             {model.json,monitor/battery.json,monitor/clock.json,monitor/pump-history.json,monitor/reservoir.json,monitor/status.json,monitor/temp-basal-status.json,nightscout/openaps-status.json,nightscout/preflight.json,nightscout/recent-missing-entries.json,nightscout/recent-treatments.json,nightscout/uploaded-entries.json,nightscout/uploaded-recent-devicestatus.json,nightscout/uploaded.json,oref0-enacted/enacted-temp-basal.json,oref0-predict/oref0.json,raw-pump/battery.json,raw-pump/bg-targets-raw.json,raw-pump/clock-raw.json,raw-pump/insulin-sensitivities-raw.json,raw-pump/pump-history-raw.json,raw-pump/reservoir.json,raw-pump/selected-basal-profile.json,raw-pump/settings.json,raw-pump/status.json,raw-pump/temp-basal-status.json,settings/bg-targets.json,settings/insulin-sensitivities.json,settings/selected-basal-profile.json,settings/settings.json}
                             [{model.json,monitor/battery.json,monitor/clock.json,monitor/pump-history.json,monitor/reservoir.json,monitor/status.json,monitor/temp-basal-status.json,nightscout/openaps-status.json,nightscout/preflight.json,nightscout/recent-missing-entries.json,nightscout/recent-treatments.json,nightscout/uploaded-entries.json,nightscout/uploaded-recent-devicestatus.json,nightscout/uploaded.json,oref0-enacted/enacted-temp-basal.json,oref0-predict/oref0.json,raw-pump/battery.json,raw-pump/bg-targets-raw.json,raw-pump/clock-raw.json,raw-pump/insulin-sensitivities-raw.json,raw-pump/pump-history-raw.json,raw-pump/reservoir.json,raw-pump/selected-basal-profile.json,raw-pump/settings.json,raw-pump/status.json,raw-pump/temp-basal-status.json,settings/bg-targets.json,settings/insulin-sensitivities.json,settings/selected-basal-profile.json,settings/settings.json} ...]
openaps-report invoke: error: argument report: invalid choice: 'raw-cgm/glucose-raw.json' (choose from u'model.json', u'monitor/battery.json', u'monitor/clock.json', u'monitor/pump-history.json', u'monitor/reservoir.json', u'monitor/status.json', u'monitor/temp-basal-status.json', u'nightscout/openaps-status.json', u'nightscout/preflight.json', u'nightscout/recent-missing-entries.json', u'nightscout/recent-treatments.json', u'nightscout/uploaded-entries.json', u'nightscout/uploaded-recent-devicestatus.json', u'nightscout/uploaded.json', u'oref0-enacted/enacted-temp-basal.json', u'oref0-predict/oref0.json', u'raw-pump/battery.json', u'raw-pump/bg-targets-raw.json', u'raw-pump/clock-raw.json', u'raw-pump/insulin-sensitivities-raw.json', u'raw-pump/pump-history-raw.json', u'raw-pump/reservoir.json', u'raw-pump/selected-basal-profile.json', u'raw-pump/settings.json', u'raw-pump/status.json', u'raw-pump/temp-basal-status.json', u'settings/bg-targets.json', u'settings/insulin-sensitivities.json', u'settings/selected-basal-profile.json', u'settings/settings.json')
ns://JSON/shell/nightscout/recent-treatments.json
Could not parse pumphistory:  { [Error: Cannot find module '/home/pi/my_openaps/monitor/pump-history.json'] code: 'MODULE_NOT_FOUND' }
No JSON object could be decoded

Traceback (most recent call last):
  File "/usr/local/bin/openaps-report", line 4, in <module>
    __import__('pkg_resources').run_script('openaps==0.1.5', 'openaps-report')
  File "build/bdist.linux-armv7l/egg/pkg_resources/__init__.py", line 719, in run_script
  File "build/bdist.linux-armv7l/egg/pkg_resources/__init__.py", line 1504, in run_script
  File "/usr/local/lib/python2.7/dist-packages/openaps-0.1.5-py2.7.egg/EGG-INFO/scripts/openaps-report", line 82, in <module>
    app( )
  File "/usr/local/lib/python2.7/dist-packages/openaps-0.1.5-py2.7.egg/openaps/cli/__init__.py", line 51, in __call__
    self.run(self.args)
  File "/usr/local/lib/python2.7/dist-packages/openaps-0.1.5-py2.7.egg/EGG-INFO/scripts/openaps-report", line 75, in run
    output = app(args, self)
  File "/usr/local/lib/python2.7/dist-packages/openaps-0.1.5-py2.7.egg/openaps/cli/subcommand.py", line 52, in __call__
    return self.method.main(args, app)
  File "/usr/local/lib/python2.7/dist-packages/openaps-0.1.5-py2.7.egg/openaps/reports/invoke.py", line 48, in main
    reporters.Reporter(report, device, task)(output)
  File "/usr/local/lib/python2.7/dist-packages/openaps-0.1.5-py2.7.egg/openaps/reports/reporters/__init__.py", line 33, in __call__
    self.blob = self.serialize(data)
  File "/usr/local/lib/python2.7/dist-packages/openaps-0.1.5-py2.7.egg/openaps/reports/reporters/__init__.py", line 31, in serialize
    return self.method.serialize(render(data), self)
  File "/usr/local/lib/python2.7/dist-packages/openaps-0.1.5-py2.7.egg/openaps/vendors/process.py", line 56, in prerender_json
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
pi@raspberrypi:~/my_openaps $ 

----

**Comment by walker0** [comment]
Hi Luis, it is probably best if you head over to the Gitter channel at  https://gitter.im/nightscout/intend-to-bolus  and ask there

**Comment by danamlewis** [comment]
Hi @betluis - I think we helped you on Gitter. I am closing this issue, but please ask in Gitter if this wasn't resolved for you.
