### ISSUE TITLE
Broken Link: Guide to Understanding the OpenAPS Toolkit

### ISSUE THREAD

**Issue by Praxiteles** [openaps/docs#437]
This link is broken: 
Guide to understanding the openaps toolkit

on this page: https://github.com/openaps/docs/blob/master/docs/docs/walkthrough/manual/phase-1/using-openaps-tools.md

**Comment by danamlewis** [comment]
@Praxiteles fixed via https://github.com/openaps/docs/commit/4e9ee124d3f516818134e6200bd3339b920ca785, thanks.
