### ISSUE TITLE
Installing from source fails

### ISSUE THREAD

**Issue by eyim** [openaps/docs#48]
The script on installing from source from this page doesn't work:

https://openaps.gitbooks.io/building-an-open-artificial-pancreas-system/content/docs/getting-started/openaps.html

curl -s https://raw.githubusercontent.com/openaps/docs/master/scripts/quick-src.sh | bash -

Here are the error messages I received:

Get:1 http://mirrordirector.raspbian.org/raspbian/ jessie/main libpython2.7-dev                                                                                                                                                              armhf 2.7.9-2 [17.9 MB]
Err http://mirrordirector.raspbian.org/raspbian/ jessie/main libssl-dev armhf 1.                                                                                                                                                             0.1k-3+deb8u1
  404  Not Found [IP: 5.153.225.207 80]
Err http://mirrordirector.raspbian.org/raspbian/ jessie/main libssl-doc all 1.0.                                                                                                                                                             1k-3+deb8u1
  404  Not Found [IP: 5.153.225.207 80]
Get:2 http://mirrordirector.raspbian.org/raspbian/ jessie/main python-dev armhf                                                                                                                                                              2.7.9-1 [1,188 B]
Get:3 http://mirrordirector.raspbian.org/raspbian/ jessie/main python-apt armhf                                                                                                                                                              0.9.3.12 [156 kB]
Get:4 http://mirrordirector.raspbian.org/raspbian/ jessie/main gyp all 0.1~svn17                                                                                                                                                             29-3 [201 kB]
Get:5 http://mirrordirector.raspbian.org/raspbian/ jessie/main libjs-node-uuid a                                                                                                                                                             ll 1.4.0-1 [12.6 kB]
Get:6 http://mirrordirector.raspbian.org/raspbian/ jessie/main libjs-underscore                                                                                                                                                              all 1.7.0~dfsg-1 [49.9 kB]
Get:7 http://mirrordirector.raspbian.org/raspbian/ jessie/main libpython-dev arm                                                                                                                                                             hf 2.7.9-1 [19.6 kB]
Get:8 http://mirrordirector.raspbian.org/raspbian/ jessie/main libv8-3.14-dev ar                                                                                                                                                             mhf 3.14.5.8-8.1+rpi1 [108 kB]
Get:9 http://mirrordirector.raspbian.org/raspbian/ jessie/main node-async all 0.                                                                                                                                                             8.0-1 [24.6 kB]
Get:10 http://mirrordirector.raspbian.org/raspbian/ jessie/main node-node-uuid a                                                                                                                                                             ll 1.4.0-1 [9,194 B]
Get:11 http://mirrordirector.raspbian.org/raspbian/ jessie/main node-underscore                                                                                                                                                              all 1.7.0~dfsg-1 [34.2 kB]
Get:12 http://mirrordirector.raspbian.org/raspbian/ jessie/main python2.7-dev ar                                                                                                                                                             mhf 2.7.9-2 [281 kB]
Get:13 http://mirrordirector.raspbian.org/raspbian/ jessie/main unattended-upgra                                                                                                                                                             des all 0.81+rpi1 [45.7 kB]
Get:14 http://mirrordirector.raspbian.org/raspbian/ jessie/main python-software-                                                                                                                                                             properties all 0.92.25debian1 [42.1 kB]
Get:15 http://mirrordirector.raspbian.org/raspbian/ jessie/main libc-ares-dev ar                                                                                                                                                             mhf 1.10.0-2 [140 kB]
Get:16 http://mirrordirector.raspbian.org/raspbian/ jessie/main node-abbrev all                                                                                                                                                              1.0.5-2 [3,540 B]
Get:17 http://mirrordirector.raspbian.org/raspbian/ jessie/main node-ansi all 0.                                                                                                                                                             3.0-2 [8,608 B]
Get:18 http://mirrordirector.raspbian.org/raspbian/ jessie/main node-ansi-color-                                                                                                                                                             table all 1.0.0-1 [4,408 B]
Get:19 http://mirrordirector.raspbian.org/raspbian/ jessie/main node-archy all 0                                                                                                                                                             .0.2-1 [3,620 B]
Get:20 http://mirrordirector.raspbian.org/raspbian/ jessie/main node-inherits al                                                                                                                                                             l 2.0.1-1 [3,230 B]
Get:21 http://mirrordirector.raspbian.org/raspbian/ jessie/main node-block-strea                                                                                                                                                             m all 0.0.7-1 [4,550 B]
Get:22 http://mirrordirector.raspbian.org/raspbian/ jessie/main node-delayed-str                                                                                                                                                             eam all 0.0.5-1 [4,482 B]
Get:23 http://mirrordirector.raspbian.org/raspbian/ jessie/main node-combined-st                                                                                                                                                             ream all 0.0.5-1 [4,918 B]
Get:24 http://mirrordirector.raspbian.org/raspbian/ jessie/main node-cookie-jar                                                                                                                                                              all 0.3.1-1 [3,570 B]
Get:25 http://mirrordirector.raspbian.org/raspbian/ jessie/main node-forever-age                                                                                                                                                             nt all 0.5.1-1 [3,066 B]
Get:26 http://mirrordirector.raspbian.org/raspbian/ jessie/main node-mime all 1.                                                                                                                                                             2.11-1 [18.1 kB]
Get:27 http://mirrordirector.raspbian.org/raspbian/ jessie/main node-form-data a                                                                                                                                                             ll 0.1.0-1 [6,084 B]
Get:28 http://mirrordirector.raspbian.org/raspbian/ jessie/main node-rimraf all                                                                                                                                                              2.2.8-1 [5,668 B]
Get:29 http://mirrordirector.raspbian.org/raspbian/ jessie/main node-mkdirp all                                                                                                                                                              0.5.0-1 [4,634 B]
Get:30 http://mirrordirector.raspbian.org/raspbian/ jessie/main node-graceful-fs                                                                                                                                                              all 3.0.2-1 [7,070 B]
Get:31 http://mirrordirector.raspbian.org/raspbian/ jessie/main node-fstream all                                                                                                                                                              0.1.24-1 [17.5 kB]
Get:32 http://mirrordirector.raspbian.org/raspbian/ jessie/main node-lru-cache a                                                                                                                                                             ll 2.3.1-1 [5,344 B]
Get:33 http://mirrordirector.raspbian.org/raspbian/ jessie/main node-sigmund all                                                                                                                                                              1.0.0-1 [3,750 B]
Get:34 http://mirrordirector.raspbian.org/raspbian/ jessie/main node-minimatch a                                                                                                                                                             ll 1.0.0-1 [13.9 kB]
Get:35 http://mirrordirector.raspbian.org/raspbian/ jessie/main node-fstream-ign                                                                                                                                                             ore all 0.0.6-2 [5,536 B]
Get:36 http://mirrordirector.raspbian.org/raspbian/ jessie/main node-github-url-                                                                                                                                                             from-git all 1.1.1-1 [2,986 B]
Get:37 http://mirrordirector.raspbian.org/raspbian/ jessie/main node-once all 1.                                                                                                                                                             1.1-1 [2,552 B]
Get:38 http://mirrordirector.raspbian.org/raspbian/ jessie/main node-glob all 4.                                                                                                                                                             0.5-1 [13.1 kB]
Get:39 http://mirrordirector.raspbian.org/raspbian/ jessie/main nodejs-dev armhf                                                                                                                                                              0.10.29~dfsg-2 [247 kB]
Get:40 http://mirrordirector.raspbian.org/raspbian/ jessie/main node-nopt all 3.                                                                                                                                                             0.1-1 [9,484 B]
Get:41 http://mirrordirector.raspbian.org/raspbian/ jessie/main node-npmlog all                                                                                                                                                              0.0.4-1 [5,516 B]
Get:42 http://mirrordirector.raspbian.org/raspbian/ jessie/main node-osenv all 0                                                                                                                                                             .1.0-1 [3,734 B]
Get:43 http://mirrordirector.raspbian.org/raspbian/ jessie/main node-tunnel-agen                                                                                                                                                             t all 0.3.1-1 [3,840 B]
Get:44 http://mirrordirector.raspbian.org/raspbian/ jessie/main node-json-string                                                                                                                                                             ify-safe all 5.0.0-1 [3,356 B]
Get:45 http://mirrordirector.raspbian.org/raspbian/ jessie/main node-qs all 2.2.                                                                                                                                                             4-1 [8,474 B]
Get:46 http://mirrordirector.raspbian.org/raspbian/ jessie/main node-request all                                                                                                                                                              2.26.1-1 [15.7 kB]
Get:47 http://mirrordirector.raspbian.org/raspbian/ jessie/main node-semver all 2.1.0-2 [14.9 kB]
Get:48 http://mirrordirector.raspbian.org/raspbian/ jessie/main node-tar all 0.1.18-1 [16.9 kB]
Get:49 http://mirrordirector.raspbian.org/raspbian/ jessie/main node-which all 1.0.5-2 [3,610 B]
Get:50 http://mirrordirector.raspbian.org/raspbian/ jessie/main node-gyp all 0.12.2+ds-1 [19.4 kB]
Get:51 http://mirrordirector.raspbian.org/raspbian/ jessie/main node-ini all 1.1.0-1 [4,720 B]
Get:52 http://mirrordirector.raspbian.org/raspbian/ jessie/main node-lockfile all 0.4.1-1 [5,150 B]
Get:53 http://mirrordirector.raspbian.org/raspbian/ jessie/main node-mute-stream all 0.0.4-1 [4,056 B]
Get:54 http://mirrordirector.raspbian.org/raspbian/ jessie/main node-normalize-package-data all 0.2.2-1 [8,604 B]
Get:55 http://mirrordirector.raspbian.org/raspbian/ jessie/main node-read all 1.0.5-1 [4,262 B]
Get:56 http://mirrordirector.raspbian.org/raspbian/ jessie/main node-read-package-json all 1.2.4-1 [7,740 B]
Get:57 http://mirrordirector.raspbian.org/raspbian/ jessie/main node-retry all 0.6.0-1 [6,124 B]
Get:58 http://mirrordirector.raspbian.org/raspbian/ jessie/main node-sha all 1.2.3-1 [4,064 B]
Get:59 http://mirrordirector.raspbian.org/raspbian/ jessie/main node-slide all 1.1.4-1 [6,078 B]
Get:60 http://mirrordirector.raspbian.org/raspbian/ jessie/main npm all 1.4.21+ds-2 [354 kB]
Get:61 http://mirrordirector.raspbian.org/raspbian/ jessie/main watchdog armhf 5.14-3 [78.1 kB]
Fetched 20.0 MB in 18s (1,094 kB/s)
E: Failed to fetch http://mirrordirector.raspbian.org/raspbian/pool/main/o/openssl/libssl-dev_1.0.1k-3+deb8u1_armhf.deb  404  Not Found [IP: 5.153.225.207 80]

E: Failed to fetch http://mirrordirector.raspbian.org/raspbian/pool/main/o/openssl/libssl-doc_1.0.1k-3+deb8u1_all.deb  404  Not Found [IP: 5.153.225.207 80]

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
bash: line 8: cd: src: No such file or directory
sudo: openaps-install-udev-rules: command not found

**Comment by scottleibrand** [comment]
Hmm. That looks like a problem with the Raspbian repo. Wonder if we should have people add another mirror in case the main mirrordirector breaks (as it often seems to).

**Comment by scottleibrand** [comment]
Specifically, you could try adding `deb http://archive.raspbian.org/raspbian wheezy main contrib non-free` to `/etc/apt/sources.list` and re-try quick-src.sh.

**Comment by eyim** [comment]
I made the changes and ran the script twice but still it didn't work.  Here is the error from the second time I ran it:

Err http://mirrordirector.raspbian.org/raspbian/ jessie/main libssl-dev armhf 1.0.1k-3+deb8u1
  404  Not Found [IP: 5.153.225.207 80]
Err http://mirrordirector.raspbian.org/raspbian/ jessie/main libssl-doc all 1.0.1k-3+deb8u1
  404  Not Found [IP: 5.153.225.207 80]
E: Failed to fetch http://mirrordirector.raspbian.org/raspbian/pool/main/o/openssl/libssl-dev_1.0.1k-3+deb8u1_armhf.deb  404  Not Found [IP: 5.153.225.207 80]

E: Failed to fetch http://mirrordirector.raspbian.org/raspbian/pool/main/o/openssl/libssl-doc_1.0.1k-3+deb8u1_all.deb  404  Not Found [IP: 5.153.225.207 80]

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
bash: line 8: cd: src: No such file or directory
sudo: openaps-install-udev-rules: command not found

**Comment by daranday** [comment]
Why is this closed, I just encountered this error too.

**Comment by scottleibrand** [comment]
I closed this because I was unable to reproduce it, and simply due to age.  Please reopen (or open a new issue) and include some additional details on what you're seeing, and I'll be happy to look into it with you.

**Comment by eyim** [comment]
We did fix the error that I found.  Maybe it is a new bug.  

Edward

**Comment by daranday** [comment]
I'm in the US and the default server was not working. I turned to the
Canada mirror:

# /etc/apt/sources.list :
deb http://ftp.ca.debian.org/debian/ jessie main contrib non-free
deb-src http://ftp.ca.debian.org/debian/ jessie main contrib non-free

which allowed me to apt-get install successfully, but  because I'm using
Jessie on B+ which does not support armv7, the install package says illegal
instruction when trying to use the vlc command. I've switched back to
Wheezy.

Thanks,
Daran

B.S. - Computer Science and Physics, Class of 2015
University of Michigan

**Comment by scottleibrand** [comment]
Do you think we need to update the docs or scripts to handle either of those cases?  And if so, how would you suggest we do so?

**Comment by daranday** [comment]
Just update the default server in the /etc/apt/sources.list should help a
lot.

B.S. - Computer Science and Physics, Class of 2015
University of Michigan

**Comment by scottleibrand** [comment]
Would you care to PR in directions on how to do that, and when/why someone might want to?  It would probably go at https://github.com/openaps/docs/blob/dev/docs/docs/walkthrough/phase-0/rpi.md#update-the-raspberry-pi-optional and/or https://github.com/openaps/docs/blob/dev/docs/docs/Resources/troubleshooting.md
