### ISSUE TITLE
Possible hiccup during jubilinux flashing

### ISSUE THREAD

**Issue by beached** [openaps/docs#515]
While flashing my Edison from Ubilinux to Jubilinux it timed out waiting for the reboot after repartitioning
Rebooting to apply partition changes
Now waiting for dfu device 8087:0a99
Timed out while waiting for dfu device 8087:0a99

Running it again, successfully flashed the device.

**Comment by scottleibrand** [comment]
Were you watching it on console at the time? Did it give you a Ctrl-D prompt?

**Comment by beached** [comment]
The device rebooted to the previous install, verified by logging in and checking configs i had there(so same all around)

**Comment by beached** [comment]
An additional note, I rebooted again just in case too.  Then just ran flashall.sh again
