### ISSUE TITLE
Documenting G5 

### ISSUE THREAD

**Issue by danamlewis** [openaps/docs#56]
Needs further documentation - and is dependent on decoding-dexcom - someone needs to update it to detect which version receiver you have plugged in. Once this is done, openaps docs will need to be updated to note that G5 works.

**Comment by bewest** [comment]
Covered in https://github.com/openaps/docs/pull/134.  G5 usb support ships with openaps now, and is configured with: `openaps use cgm config --G5`.

**Comment by scottleibrand** [comment]
Has this now been completed?  Should we close it?
