### ISSUE TITLE
Document variables and determine-basal output

### ISSUE THREAD

**Issue by danamlewis** [openaps/docs#57]
Variables and determine-basal output need to be documented by an experienced looper to help new loopers working through this process. @scottleibrand is assigned to this.

**Comment by ehwest** [comment]
The algorithm provided fails to define:
"Eventual BG"  and "Target"
Please define these and show how they are calculated.

**Comment by scottleibrand** [comment]
Those are already defined in the reference design: https://github.com/openaps/docs/blob/master/reference-design.md

If you'd like it to be more clear in this document, feel free to propose clarifying language or links. Or if it's still not clear from reading the reference design and other docs (for example, the part about setting up a report to pull BG targets from the pump), feel free to ask clarifying questions.
