### ISSUE TITLE
Openaps Writing Rasbian Jessie Lite to SD Card

### ISSUE THREAD

**Issue by MicheleJustine** [openaps/docs#617]
Hi,
I am in the process of setting up openaps and at the stage of writing rasbian jessie to my SD card on a mac. However, when I use terminal to type in my image path: 2017-01-11-raspbian-jessie-lite.img , it says the file/directory doesn't exist. When I go to the finder and type in the path, rasbian jessie pops up, showing me it has the same pathway I was typing in the terminal. If anyone could give some suggestions  that would be of great help!

**Comment by scottleibrand** [comment]
You're probably just starting in the wrong directory. If you put it in Downloads, you can get there via `cd ~/Downloads`

**Comment by scottleibrand** [comment]
Sounds like you found Gitter though. That is best for troubleshooting.
