### ISSUE TITLE
SD Card Writing

### ISSUE THREAD

**Issue by MicheleJustine** [openaps/docs#627]
I have used terminal and written rasbian jessie to my SD card but I'm not sure how to tell when it has successfully finished writing. I tried using the command CTRL+T but I'm don't know what the information it is showing means or how to tell if it has completed the process. 😬

**Comment by scottleibrand** [comment]
It'll be obvious when it's done: you'll get your prompt back. 😀

The Ctrl-T output shows the number of bytes written. You can compare that to the size of your image file in bytes to see how much is done/left.

**Comment by MicheleJustine** [comment]
Thanks!
