### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by eyim** [openaps/docs#64]
The phase visualization link on this page:

https://openaps.gitbooks.io/building-an-open-artificial-pancreas-system/content/index.html

goes to a 404 page

https://github.com/openaps/docs/blob/master/docs/OpenAPS_phase_visualization_Nov152015.png

**Comment by danamlewis** [comment]
Can you check and see if it is broken on github too, or just gitbook?

On Saturday, January 2, 2016, eyim <notifications@github.com> wrote:

> The phase visualization link on this page:
>
>
> https://openaps.gitbooks.io/building-an-open-artificial-pancreas-system/content/index.html
>
> goes to a 404 page
>
>
> https://github.com/openaps/docs/blob/master/docs/OpenAPS_phase_visualization_Nov152015.png
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openaps/docs/issues/64>.
>


-- 
Dana Lewis | http://diyps.org | @DanaMLewis
<http://www.twitter.com/danamlewis> | http://www.linkedin.com/in/danalewis
"Doing something for someone else is more important than anything you would
do for yourself."

**Comment by eyim** [comment]
Yes it breaks even when I click on the link on this github page:

https://github.com/openaps/docs

**Comment by scottleibrand** [comment]
Fixed.
