### ISSUE TITLE
Dexcom share instead of nightscout

### ISSUE THREAD

**Issue by MicheleJustine** [openaps/docs#675]
Hi, I use a dexcom G5 sensor and the dexcom share app to view my bg on my phone, would it be possible to use this with openaps setup instead of nightscout?

**Comment by scottleibrand** [comment]
You can easily configure Nightscout to pull the CGM data from Dexcom's Share servers. That option should be recommended in the docs already; if it's not, a PR to clarify would be most welcome.

**Comment by MicheleJustine** [comment]
Thank you. We just got share in canada so its all new to us!

**Comment by scottleibrand** [comment]
Let us know in ITB if you have any trouble getting this set up. Thanks!
