### ISSUE TITLE
advocacy language for talking to MiniMed

### ISSUE THREAD

**Issue by eszcloud** [openaps/docs#84]
What language to use when talking to MiniMed so that they are getting feedback at all different levels that users need access to their devices? What are the key words to say, points to make, etc. so that there is a consistent message?

**Comment by danamlewis** [comment]
Will incorporate into the next outline. So closing this but added a note there (https://github.com/openaps/docs/commit/8ac49f7b0516f145befd8c893b2eb5fb66677f23#diff-ce47a30eb7f9e453a3ca1c86bcf2f2fa) to fold this in.
