### ISSUE TITLE
Nightscout back fill configs

### ISSUE THREAD

**Issue by sillystring13** [openaps/docs#851]
Nightscout doesn't automatically back fill CGM data even when Share does.  If your routine includes gaps in transmitter connectivity and data uploads, this may affect your calculations.

I suggest that we include instructions on best practices in configuring NS to backfill.  Opening issue to discuss what the best practice recommendations would be.

**Comment by PieterGit** [comment]
I use @ecc1 https://github.com/ecc1/backfill with a Dexcom G4. Don't know if it also works for G5. I am planning to write a `buffered-curl` command for `CGM=G4-upload` that will also upload missed cgm later when the rig is online.

**Comment by danamlewis** [comment]
👍 added https://github.com/openaps/docs/pull/852 into the docs

**Comment by danamlewis** [comment]
Closing, since referenced in the docs.
