### ISSUE TITLE
no Understand-determine-basal.md in gitbooks

### ISSUE THREAD

**Issue by lukasz-kaniowski** [openaps/docs#97]
Seems that `Understand-determine-basal.md` is not deployed correctly in gitbooks. See below:
<img width="292" alt="using_oref0_tools___building_an_open_artificial_pancreas_system" src="https://cloud.githubusercontent.com/assets/174123/13731854/be6f4c9e-e96b-11e5-95ee-95a90dd35214.png">

**Comment by scottleibrand** [comment]
We are trying to deprecate gitbooks.  Where do you still see links to it?  We'd rather delete them all so people stop trying to use it.

**Comment by lukasz-kaniowski** [comment]
Hmm, actually I don't remember. I think that I googled "openaps documentation" or similar.

**Comment by scottleibrand** [comment]
The gitbook has now been removed.  Going through all the docs and removing references to it.  If you come across any, please PR to fix.
