### ISSUE TITLE
Intel Edison recommended in docs, but device is discontinued! (Last buy September 16, 2017)

### ISSUE THREAD

**Issue by Black-Magic** [openaps/docs#976]
It appears that the documentation and software(?) will need revision - and a new hardware home

https://communities.intel.com/docs/DOC-112093
**Intel will support last time orders of Intel Edison products through September 16, 2017 and will fulfill those orders through December 16, 2017.** 

> Intel® Edison Discontinuation Notice: Version 1
Created by MTaylor on Jul 5, 2017 3:46 PM. Last modified by MTaylor on Jul 5, 2017 3:46 PM.
Intel is discontinuing Intel® Edison compute modules and developer kits. To help customers manage through the Intel Edison discontinuance, Intel will support last time orders of Intel Edison products through September 16, 2017 and will fulfill those orders through December 16, 2017. The current level of community forum-based support for Intel Edison will continue to be available through September 15, 2017. There are no further software releases planned for the Intel Edison platform. After September 15, 2017, Intel will archive its online resources and maintain availability to the Intel Edison community until June 15, 2020. Files licensed under open source licenses will continue to be generally available in binary and source code on GitHub.

**Comment by danamlewis** [comment]
There is predicted to be plenty of stock through the end of the year, so Edison is continuing to be the recommended setup for now and will be supported by the community into the future.

There's ongoing work to adapt the Explorer Board to other devices (still TBD for final decision, but PiZeroW and CHIP are contenders) and find the next recommended hardware solution, which will then be added to the docs once it's decided and available.

Whichever solution, it will be Linux based so software won't need revision, just new setup instructions.

**Comment by Black-Magic** [comment]
Excellent.

My $0.0001 worth... Chip would get my vote for not relying on flaky SD 
cards for the holding the OS. I know there will be many other aspects to 
consider though!
